version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-queue
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: redis-client-app
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  redis_data: